services:
  - type: web
    name: webpush-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VAPID_PRIVATE_KEY
        value: your_vapid_private_key_here
      - key: VAPID_PUBLIC_KEY
        value: your_vapid_public_key_here